#from Old.Grammar.Behaviours_in_use.Init_Neurons import *
#from Old.Grammar.Behaviours_in_use.Init_Synapses import *
#from Old.Grammar.Behaviours_in_use.IP import *
#from Old.Grammar.Behaviours_in_use.ISI_Inhibition_Module import *
#from Old.Grammar.Behaviours_in_use.KWTA import *
#from Old.Grammar.Behaviours_in_use.Learning import *
#from Old.Grammar.Behaviours_in_use.Output_Generation import *
#from Old.Grammar.Behaviours_in_use.Refractory import *
#from Old.Grammar.Behaviours_in_use.SynapseOperation import *
#from Old.Grammar.Behaviours_in_use.TextActivator import *
#from Old.Grammar.Behaviours_in_use.TextGeneratior import *
#from Old.Grammar.Behaviours_in_use.TextReconstructor import *
#from Old.Grammar.Behaviours_in_use.Behaviour_Bar_Activator import *
#from Old.Grammar.Behaviours_in_use.MNISTActivator import *
#from Old.Grammar.Behaviours_in_use.test import *
#from Old.Grammar.Behaviours_in_use.Out_Normalization import *