from Grammar.SORN_Grammar.Behaviours_in_use.Init_Neurons import *
from Grammar.SORN_Grammar.Behaviours_in_use.Init_Synapses import *
from Grammar.SORN_Grammar.Behaviours_in_use.IP import *
from Grammar.SORN_Grammar.Behaviours_in_use.ISI_Inhibition_Module import *
from Grammar.SORN_Grammar.Behaviours_in_use.KWTA import *
from Grammar.SORN_Grammar.Behaviours_in_use.Learning import *
from Grammar.SORN_Grammar.Behaviours_in_use.Output_Generation import *
from Grammar.SORN_Grammar.Behaviours_in_use.Refractory import *
from Grammar.SORN_Grammar.Behaviours_in_use.Synapse_Operation import *
from Grammar.SORN_Grammar.Behaviours_in_use.Text_Activator import *
from Grammar.SORN_Grammar.Behaviours_in_use.Text_Generatior import *
from Grammar.SORN_Grammar.Behaviours_in_use.Text_Reconstructor import *
from Grammar.SORN_Grammar.Behaviours_in_use.LineActivator import *
from Grammar.SORN_Grammar.Behaviours_in_use.MNISTActivator import *
from Grammar.SORN_Grammar.Behaviours_in_use.test import *